### ISSUE TITLE
Campaign Retiring - Epic

### ISSUE THREAD

**Issue by jkueloc** [LibraryOfCongress/concordia#1611]
Campaign Sunsetting - Epic

Supporting document: https://staff.loc.gov/wikis/x/ve_hBQ

- [ ] Define, design and build Report for capturing the sunset campaign's metrics #1623 
- [ ] New model/database representation - to capture metrics of retired campaigns for dashboard representation. At first initial thought, this will be an action within a Campaign Module
       - for reference see existing model graph here #1530
- [ ] New model/database representation - to capture metrics of retired campaigns tied to the user profile contribution page. Tag tied to user-asset-tag-collection (-tag), transcription tied to asset, etc.
- [ ] Modify user profile contribution page for sunset campaign contributions

**Comment by jkueloc** [comment]
This Epic moved to Jira [CONCD-9](https://staff.loc.gov/tasks/browse/CONCD-9)
