### ISSUE TITLE
A clearer connection between user research and improve features

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#524]
This epic address the need to make a clear, explicit connection between design decisions, best practices and user research. 

Issues include: 

- [ ] Use opportunities in current workflow to understand a user's experiences ie when a volunteer uses the contact us form
- [ ] Create user testing plan for specific work flows 
- [ ] Generate mocks of potential pathways and test among users

We know we are successful when:

**Comment by elainekamlley** [comment]
User testing documentation has been drafted and includes tools that we can use. At this time, we are still determining what area of the site would be valuable to focus research efforts towards.
