### ISSUE TITLE
Roadmap for the next quarter 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#556]
Develop a roadmap for the next three months. Goal is reground in our design principles, develop a product strategy, define our product goals and determine metrics to measure if we are headed in the right direction. 

Acceptance criteria: 
- [x] facilitate roadmap challege with team
- [x] Circulate among key stakeholders
- [x] Make roadmap public via a project on GitHub

**Comment by elainekamlley** [comment]
Link to [roadmap](https://github.com/LibraryOfCongress/concordia/projects/9)
