### ISSUE TITLE
Create a better onboarding experience for users

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#607]
This addresses the need to understand and build upon how users are welcomed on our site. We want users to know that we care about you and value the time you spend on crowd.loc.gov. This includes diversifying how we provide contextual information to users. 

Issues include: 

- [x] Help popovers on the transcription page
- [x] Make guides easily findable
- [x] Refinement of registration process including a welcome email after successful activation

We know we are successful:

**Comment by rstorey** [comment]
Done with #1128
