### ISSUE TITLE
Improve the pathways for discovery for users

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#608]
This issue addresses the need to understand and build improve pathways for discovery for users. Users should be able to find tasks that fit their goals, motivations and time with ease. 

Issues include: 

- [ ] Provide options for users based on their last completed task
- [x] Easily find things to do without having to go through all campaigns
- [ ] User can discover various items by tags
- [ ] Uplift search functionality to users

We will know we are successful when:

**Comment by acdha** [comment]
Should this be an issue or a project?
