### ISSUE TITLE
Refine activity tracking on user profile 

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#609]
This addresses the need of providing additional context to users. We aim to provide users with information that values their time, builds community, and makes volunteers confident to take on the tasks. 

Issues include: 

- [ ] Improve volunteer profile page to include all of their activity and totals #532 
- [ ] Details or summary of activity on an asset
- [ ] Latest activity uplifted on the home page ex. total contributions, completed transcriptions, total volunteers, etc.

We know we are successful when:

**Comment by lalgee** [comment]
Additional related tickets

- [ ] Engage History Hub Users on how to improve user profile https://github.com/LibraryOfCongress/concordia/issues/621
- [ ] Add newsletter opt in/out https://github.com/LibraryOfCongress/concordia/issues/659
- [ ] Break out My Contributions Campaign level Actions into Transcribe & Review https://github.com/LibraryOfCongress/concordia/issues/723
- [ ] Add tag activity https://github.com/LibraryOfCongress/concordia/issues/834

**Comment by elainekamlley** [comment]
Outdated ticket and will focus on more specific tickets
