### ISSUE TITLE
Improve documentation for various audiences

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#610]
This addresses the need to expand documentation for our internal colleagues at the Library to a technical audience looking to take our code. This is aligned with the design principle of "Sustaining and improving workflows and participation".

Issues include: 
- [ ] Up to date technical docs to stand up a separate instance of Concordia #529 
- [ ] Build out internal documentation for internal staff to stay up to date with progress of the program
- [ ] Capture process of communication, events, and program related operations
- [ ] One pagers and handouts for conferences 

We know we are successful when:
