### ISSUE TITLE
Convert UI assessment email to actionable tickets

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#821]
- [ ]   Bootstrap scss implementation has to happen first. #841 
- [ ]   Second step would be to redo the header/footer and all static pages, #842, #843, #844, #846, #847
- [ ]  Last step would be to work on the asset detail and gallery view pages. #845
 
Examples built with Bootstrap scss:
about: http://lekivld03.loctest.gov/etc/bootstrap-4-theme-test/about.html
help: http://lekivld03.loctest.gov/etc/bootstrap-4-theme-test/help.html
help sub page: http://lekivld03.loctest.gov/etc/bootstrap-4-theme-test/help-transcribe.html
campaign list pages: http://lekivld03.loctest.gov/etc/bootstrap-4-theme-test/campaign-detail.html
transcription page: http://lekivld03.loctest.gov/etc/bootstrap-4-theme-test/transcription.html
