### ISSUE TITLE
Prototype punch list

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#930]
Original PR for context: #812 

# Goals: 
* Help users stay in the zone for a particular activity
* Make it easy to pick items you want to work on even if that crosses projects
* Never leave fullscreen mode unless you navigate to an external source

## Items from original list: 
* [x] Component-ize the code for the transcribe/review panel which does the right thing for mode changes and data updates (change from plain HTML to full component) (@acdha )
* [x] Determine behavior for UI feedback after button submits - modal dialog? banner? disable / enable textarea? (@acdha )
* [x] Review OpenSeadragon controls - left/right controls, fullscreen, help (@jbresner )
     * [x] OpenSeadragon Help should open Help tab on the right
     * [x] The "home" button should be grouped with the "zoom in" and "zoom out" buttons
     * [x] The left -right arrows that allow you to go to the next tile source should be (temporarily) removed (until we restore / customize the reference strip navigator)
* [x] What should the transcription text box look like when you're reviewing? Particularly when there is nothing to transcribe? (@jbresner + dev TBD)
* [x] Consistent terminology and descriptions for interface components / help guide / documentation (@elainekamlley or @lalgee ?) -- ticketed as #871
* [x] Support for non-logged in users needs to be re-implemented -- ticketed as #999
* [x] ~~What should the adjacent pages section of the OpenSeadragon viewer look like? i.e. how do we indicate which page you're transcribing and which ones are just there for context?~~ Remove the adjacent pages of OpenSeadragon viewer for now - and the Display Region Navigator -- ticketed as #1000 
* [x] Side panel help text - to what extent does this need to be editable / customizable?

## Known bugs: 
* [x] Better looking badges / UI for when something is reserved by another user (@jbresner )
* [x] Either use the footer for additional stuff or get rid of it (@jbresner + @acdha)
* [x] Fullscreen icon is missing from mocks (@jbresner )
* [x] Get rid of Display Region Navigator
* [x] Make the Help/Filmstrip tabs mutually exclusive
* [x] Don't display difficulty score in asset card hover
* [x] Make an asset hover display that works when asset list is in film strip column -- ticketed as #998 
* [x] The ? icon next to Nothing to Transcribe doesn't do anything

## Testing feedback (can be de-duped if it is captured above)
- [x] When I zoom in and then click on a page to move it after about 30 seconds or so it resets the page zoom level (and clears the textarea box if I entered text) - ticketed here: #949 
- [x] De-dupe campaign info in the info box (cadams: this needs clarification) Steps to reproduce:
1. Open an asset from the list. Click Info. Close the info box.
2. Repeat.
Observed behavior: 
1. On n>1 step, the info box contains n copies of campaign / project / item info data.
Expected behavior:
1. The info box should only contain the info for the current asset, and it should appear once.
- [x] I did not know I needed to be logged in, I expected to see a message on the page to log in so that I can perform the task
- [x] ~~`?` in viewer is disabled - I expect this button to open the same info as the `?` in the nav bar~~ see above item " Review OpenSeadragon controls - left/right controls, fullscreen, help" - I propose removing the Help button from the OpenSeadragon controls
- [x] ~~In design mocks, I see that a lock icon symbolizes that someone is on the page, Could that be a person icon instead? It's a more inviting way to show that many people collaborating~~ See above in Known Bugs "Better looking badges / UI for when something is reserved by another user"
- [x] ~~I would like start fresh and transcribe items that are not started, I expect to be able to pick this option in the sort drop down (rstorey: This is not a sort, this is a filter option, and made more complicated that it only applies in Transcribe and not in Review mode. The user could get "not started" items by choosing Transcribe mode and sorting "Easiest".)~~ -- Deferred
- [x] In sort, when I choose easiest the images still look hard, I expect images to have more legible writing. Hardest however is very obvious. Let's remove Easiest for now until we can get a better sense on we can determine easy. 
- [x] #955 When I click the more info box, I expect to see an representative image of the person or topic (rstorey: This isn't in the mocks. Does @jbresner have bandwidth to mock something using campaign / project thumbnail images?)
- [x] ~~When moving to next and previous page I only saw the image in the viewer, I expected to see the accompanying title and transcription (rstorey: This has to do with the above item "What should the adjacent pages section of the OpenSeadragon viewer look like? i.e. how do we indicate which page you're transcribing and which ones are just there for context?" as well as the item in the Deferred Features from #812 which talked about only loading the previous and next images for reference, and not for navigation - not loading the transcription data or other metadata. If that's truly a requirement, we need to rethink using the OpenSeadragon reference viewer for this purpose and instead put in a second asset list. Also, if we change the asset in the viewer when you go prev or next, you'll lose any unsaved work as well as your asset reservation).~~ Deferred 
- [x] In the sort by box, when I choose 'Most Recent', what is being shown to me? Answer: most recently worked on by someone. Edited the label to read "Most Recently Updated"

**Comment by elainekamlley** [comment]
From @jbresner 

Here are the latest set of comps for the prototype. I still have some specs I want to add but may just add them as additional comments.

![Asset View - Default View](https://user-images.githubusercontent.com/4275957/56999345-cb27a300-6b7c-11e9-91d2-ce80ca9b5e3a.png)
![Asset View - Help](https://user-images.githubusercontent.com/4275957/56999347-cb27a300-6b7c-11e9-9957-62e753d445d8.png)
![Asset View - More Info](https://user-images.githubusercontent.com/4275957/56999349-cb27a300-6b7c-11e9-8e0e-38c54802af25.png)
![Asset View - Share](https://user-images.githubusercontent.com/4275957/56999350-cb27a300-6b7c-11e9-95da-1fe517253fdd.png)
![Asset View - Slideshow Closed](https://user-images.githubusercontent.com/4275957/56999352-cb27a300-6b7c-11e9-8994-42bc7edcd4fa.png)
![Asset View - Slideshow Next Image](https://user-images.githubusercontent.com/4275957/56999353-cb27a300-6b7c-11e9-8393-81ec689ee6c1.png)
![Asset View - Tabs Closed](https://user-images.githubusercontent.com/4275957/56999354-cbc03980-6b7c-11e9-995d-2a58de46f6ed.png)
![Asset View - Thumbnail Scroll](https://user-images.githubusercontent.com/4275957/56999355-cbc03980-6b7c-11e9-8d7a-eb88c643ea7a.png)
![Flat View - All Items](https://user-images.githubusercontent.com/4275957/56999356-cbc03980-6b7c-11e9-8f5e-ad8bb575b55c.png)
![Flat View - Help](https://user-images.githubusercontent.com/4275957/56999357-cbc03980-6b7c-11e9-8645-c3865be51201.png)
![Large Image Grid](https://user-images.githubusercontent.com/4275957/56999358-cbc03980-6b7c-11e9-8926-90e2549c2ec7.png)
![Small Image Grid](https://user-images.githubusercontent.com/4275957/56999359-cbc03980-6b7c-11e9-9aa6-21e9e6662b5a.png)

**Comment by acdha** [comment]
>  When I was typing the text disappeared. It looks like the page refreshes.

Do we have any way to reproduce this? It doesn't happen currently so I'm not sure whether that's a problem their browser or something else but it's not really something we can work on as stated.

**Comment by elainekamlley** [comment]
On chrome on transcribe mode: I wrote a few words and in about 10 secs, it looks like the page refreshes and the text I have typed is gone

**Comment by acdha** [comment]
That doesn’t reproduce for me but there’s also no point in testing this until we finish the known missing features around asset reservations.

**Comment by elainekamlley** [comment]
I was able to reproduce it in dev. Type a few words wait a 10 -15 seconds and the text I typed goes away. I'm sure its connected to items on the punch list maybe asset reservation. So agree to test it again after more work has been ticked off.

**Comment by jbresner** [comment]
Two questions related to the UI:
1. Do we want to keep the Display Region Navigator (see attached image). Not sure it offers much value in navigating an image. If we keep it, I'd certainly want to test if people use it.
2. Ki's current build allows for both the Help tab and the Grid tab to be opened at the same time. That's not how I designed it and if we want both tabs opened at the same time (which I don't recommend), the tab metaphor UI probably has to change since it's not clear what tab goes with each open tray (see attached image).

![Screen Shot 2019-05-07 at 10 45 51 AM](https://user-images.githubusercontent.com/4275957/57311106-02d0a680-70b9-11e9-8a16-5290f816ad9e.png)

![TwoTabsOpened](https://user-images.githubusercontent.com/4275957/57311120-0bc17800-70b9-11e9-8f6c-dadea12f6bcc.png)

**Comment by jbresner** [comment]
Also, here's the comp for Review, which has slightly different styling for the text area box. @klee72, I'll add this to Zeplin for you.
![Asset View - Review](https://user-images.githubusercontent.com/4275957/57311261-47f4d880-70b9-11e9-99ca-77b1d9ef4bc6.png)

**Comment by acdha** [comment]
> Ki's current build allows for both the Help tab and the Grid tab to be opened at the same time. 

Those started out as separate components. We can continue to change the design to make them tabs but it will have a substantial ripple through the page structure.

**Comment by jbresner** [comment]
So hold off on tabs altogether for the initial prototype launch?

**Comment by acdha** [comment]
@jbresner No, we should work in that direction but it'll take more time to review the code for mutual-exclusivity since that didn't used to be a correct assumption

**Comment by acdha** [comment]
@jbresner One thing we should decide is what statuses trigger badging — e.g. this strikes me as less helpful than we'd like: 

![image](https://user-images.githubusercontent.com/46565/57324106-35889800-70d5-11e9-8185-286e5f99c24b.png)

**Comment by rstorey** [comment]
> I was able to reproduce it in dev. Type a few words wait a 10 -15 seconds and the text I typed goes away. I'm sure its connected to items on the punch list maybe asset reservation. So agree to test it again after more work has been ticked off.

I reproduced this today in my local dev environment. I observed the refresh after about 25-30 seconds of being idle.

**Comment by acdha** [comment]
Yes, it's the asset reservation system not being implemented yet – if it doesn't get the reservation it partially blocks the UI but the rest wasn't implemented before that merges. It'll go away when #932 lands.

**Comment by acdha** [comment]
Does anyone know what “De-dupe campaign info in the info box” on the feedback meant? I'm assuming something like text being included in both the campaign & project info, which would be a content-level issue, but it's hard to say with such vague information.

**Comment by rstorey** [comment]
> Does anyone know what “De-dupe campaign info in the info box” on the feedback meant? I'm assuming something like text being included in both the campaign & project info, which would be a content-level issue, but it's hard to say with such vague information.

It's this:
Steps to reproduce:
Open an asset from the list. Click Info. Close the info box.
Repeat.
Observed behavior:
On n>1 step, the info box contains n copies of campaign / project / item info data.
Expected behavior:
The info box should only contain the info for the current asset, and it should appear once.

**Comment by acdha** [comment]
@klee72: do you have any thoughts about this one?

> * Make an asset hover display that works when asset list is in film strip column

Based on the way the sizes are contained in the list, I suspect the answer is either going to be ruthlessly truncating the amount of information or changing it to be `position:absolute` so it can be larger than the containing element, but that will require a bit of code (maybe just reusing the Bootstrap popover we're already using in other places?) to update it when the list position changes.

**Comment by klee72** [comment]
> @klee72: do you have any thoughts about this one?
> 
> > * Make an asset hover display that works when asset list is in film strip column
> 
> Based on the way the sizes are contained in the list, I suspect the answer is either going to be ruthlessly truncating the amount of information or changing it to be `position:absolute` so it can be larger than the containing element, but that will require a bit of code (maybe just reusing the Bootstrap popover we're already using in other places?) to update it when the list position changes.

I think Bootstrap popover is the better option (left direction) as 'position: absolute' would look little wonky no matter how we place it. Another solution I can think of is that we could just rely on `title` attribute and hide the `.asset-tooltip` on edit view.

**Comment by rstorey** [comment]
All this is either done or ticketed in the backlog
