### ISSUE TITLE
Badging and confirmation messages in Activity UI

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#951]
- [x] Completed assets in the asset list are badged "Done!" with a check mark icon -- ticketed as #1003 
- [x] Assets reserved by another user are badged "Somebody is working on this page." with the existing person silhouette icon
- [x] If the user opens an asset that is reserved by another user, the message at the bottom (instead of action buttons) reads "Somebody else is working on this page. Please pick another page from the right."
- [x] It should be possible to edit and submit an in progress asset while in Review mode, then go back to reviewing. -- ticketed as #1004 
    - [x] After clicking Edit, the user should get a confirm message that reads, "Thank you for helping to review this transcription! Submit when you've finished your edits." And then the user should be able to Save and (re-)Submit for review. After that the confirm message should be "Thanks! Want to keep reviewing? Please pick another page from the right." Or instead of "pick another page", provide some kind of button / link equivalent to "Find a new page (to review)" in classic UI  -- ticketed as #1004 
    - [x] In Review mode, assets that have been rejected (by another user) and are in progress are badged "Finish this page" with a pencil icon -- ticketed as #1003 
- [x] After clicking Accept, the message at the bottom should be "Thanks! Want to keep reviewing? Please pick another page from the right." Or instead of "pick another page", provide some kind of button / link equivalent to "Find a new page (to review)" in classic UI  -- ticketed as #1004 
- [x] In Transcribe mode, assets that have been submitted for review should...disappear from the list? -- ticketed as #1003 
- [x] ~~Errors should go in a banner above the Asset Viewer (below the gray bar).~~

**Comment by acdha** [comment]
> In Transcribe mode, assets that have been submitted for review should...disappear from the list?

The policy we've been following everywhere in the UI is that we don't remove things from the list to avoid the jarring visual effect of it reflowing and to allow undoing an action — in this case, it seems useful to allow people to re-open something in case they notice a detail to correct in the just-submitted transcription.

**Comment by acdha** [comment]
> If the user opens an asset that is reserved by another user, the message at the bottom (instead of action buttons) reads "Somebody else is working on this page. Please pick another page from the right."

We should omit the last sentence here — it increases the size needed to contain the message and it's too specific about the UI.

**Comment by acdha** [comment]
> Errors should go in a banner above the Asset Viewer (below the gray bar).

This suggestion should go through the normal UX testing process. In general it's better for feedback from an action to happen in the same logical area rather than requiring the user to notice a change somewhere else, as currently implemented, and that's especially important for things which would either cause the screen to reposition or conflict with other controls.

**Comment by rstorey** [comment]
> > Errors should go in a banner above the Asset Viewer (below the gray bar).
> 
> This suggestion should go through the normal UX testing process. In general it's better for feedback from an action to happen in the same logical area, as currently implemented, rather than requiring the user to notice a change somewhere else and that's especially important for things which would either cause the screen to reposition or conflict with other controls.

Currently if an error occurs there's no feedback at all to the user. It needs to be visible somewhere other than the console.

**Comment by acdha** [comment]
> Currently if an error occurs there's no feedback at all to the user. 

Error states are currently indicated by replacing the button row with the text of the message (both the review and transcribe views use `ConditionalToolbar` for this). This is not implemented for all of the XHR paths because those involve retaining an error state across other events — e.g. we currently always display a message if you can't edit something for a reason such as not being able to review your own transcription but we need to make sure that XHR error override an otherwise allowed state.

**Comment by acdha** [comment]
https://github.com/LibraryOfCongress/concordia/pull/969 implements the XHR error display but it has some room for UI improvements. Currently it's a `.alert.alert-warning` fixed to the bottom of the screen, which is good in the sense that it's impossible to miss and prominent but could probably be tweaked considerably — perhaps something like fitting it into the action button row or otherwise making those fit together when necessary. I flagged it for @jbresner's review in case there's any obvious low-hanging fruit.

**Comment by rstorey** [comment]
This is either done or part of ticket #1003 or #1004
